# Generated by Django 5.0.6 on 2024-08-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Phone', models.IntegerField(verbose_name=10)),
                ('Date', models.DateField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('dr_id', models.IntegerField()),
                ('predict', models.ImageField(blank=True, null=True, upload_to='predictions/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Viewed', 'Viewed'), ('Completed', 'Completed')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('patient', 'patient'), ('doctor', 'Doctor')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
    ]
