# Generated by Django 5.0.6 on 2024-08-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='timestamp',
        ),
    ]
